import { Level } from "./game.model";

export const LEVELS: Level[] = [
  {
    bestMoves: 33,
    bestPushes: 8,
    data: "microban001",
    id: "microban001",
    title: "Level 01",
    shortTitle: "01",
  },
  {
    bestMoves: 16,
    bestPushes: 3,
    data: "microban002",
    id: "microban002",
    title: "Level 02",
    shortTitle: "02",
  },
  {
    bestMoves: 41,
    bestPushes: 13,
    data: "microban003",
    id: "microban003",
    title: "Level 03",
    shortTitle: "03",
  },
  {
    bestMoves: 23,
    bestPushes: 7,
    data: "microban004",
    id: "microban004",
    title: "Level 04",
    shortTitle: "04",
  },
  {
    bestMoves: 25,
    bestPushes: 8,
    data: "microban005",
    id: "microban005",
    title: "Level 05",
    shortTitle: "05",
  },
  {
    bestMoves: 26,
    bestPushes: 6,
    data: "microban007",
    id: "microban007",
    title: "Level 06",
    shortTitle: "06",
  },
  {
    bestMoves: 30,
    bestPushes: 10,
    data: "microban009",
    id: "microban009",
    title: "Level 07",
    shortTitle: "07",
  },
  {
    bestMoves: 78,
    bestPushes: 16,
    data: "microban011",
    id: "microban011",
    title: "Level 08",
    shortTitle: "08",
  },
  {
    bestMoves: 49,
    bestPushes: 11,
    data: "microban012",
    id: "microban012",
    title: "Level 09",
    shortTitle: "09",
  },
  {
    bestMoves: 52,
    bestPushes: 23,
    data: "microban013",
    id: "microban013",
    title: "Level 10",
    shortTitle: "10",
  },
];
